"""
Distinct Powers
"""


def powerf(num, power):
    """finds power of num"""
    prod = str(num)
    for _ in range(power - 1):
        res = []
        carry = 0

        for j in prod[::-1]:
            if carry:
                result = str(num * int(j) + int(carry))
            else:
                result = str(num * int(j))
            res.append(result[-1])
            carry = result[:-1]
        res.append(carry)
        res = res[::-1]
        prod = "".join(res)
    return int(prod)


def answer():
    """returns the number of distinct terms are in the sequence generated by
    2<=a<=100 and 2<=b<=100"""
    return solver(100)


def solver(n):
    """returns the number of distinct terms are in the sequence generated by
    2<=a<=n and 2<=b<=n"""
    lst = [powerf(i, j) for i in range(2, n + 1) for j in range(2, n + 1)]
    return len(sorted(set(lst)))


if __name__ == "__main__":
    print("Math029")
    print("answer() =", answer())
    print("solver(5) =", solver(5))
    print("\n")
